exports.dictionary = {
    "Sign in": "Войти",
    "Registration": "Регистрация",
    "Total": "Всего",
    "Subtotal": "Промежуточный итог",
    "Color": "Цвет",
    "Your cart": "Корзина",
    "Sort By:": "Сортировать по:",
    "Categories": "Категории",
    "Forgot password?": "Забыли пароль?",
    "Product Details": "Информация о товаре",
    "Review": "Отзыв",
    "Reviews (%s)": "Отзывы (%s)",
    "Step %s": "Шаг %s",
    "Website footer content": "Website footer content",
    "Website copyright": "Website copyright",
    "Top header content": "Top header content",
    "Header Logo": "Header Logo",
    "Main website navigation": "Main website navigation",
    "Header search bar": "Header search bar",
    "MiniCart Icon": "MiniCart Icon",
    "Checkout heading": "Checkout heading",
    "Checkout": "Оформление заказа",
    "Step indicator": "Индикатор шага",
    "Checkout page": "Страница оформления заказа",
    "Email Address": "Email адрес",
    "Shipping Address": "Адрес доставки",
    "Shipping Method": "Метод доставки",
    "Please enter shipping address information first!": "Пожалуйста, сначала введите информацию о доставке!",
    "Order Summary (%s)": "Итоговая сумма заказа (%s)",
    "Cart Thumbnail": "Миниатюра корзины",
    "Color:": "Цвет:",
    "Qty:": "Кол-во:",
    "Tax": "Налог",
    "The account sign-in was incorrect or your account is disabled temporarily. Please wait and try again later.":"Вы ввели неправильный пароль. Пожалуйста, повторите попытку",
    "Product Price": "Стоимость товара",
    "Current product price": "Текущая стоимость товара",
    "Old product price": "Старая стоимость товара",
    "off": "off",
    "Email is invalid.": "Некорректный Email.",
    "Password should be at least 8 characters long, include at least on upper case letter, number and symbol!": "Пароль должен содержать не менее 8 символов, включая как минимум одну заглавную букву и цифру!",
    "Phone number is invalid!": "Некорректный номер телефона!",
    "This field is required!": "Это поле обязательно к заполнению!",
    "No products found!": "Не найдено ни одного товара!",
    "Breadcrumbs (current location)...": "Хлебные крошки (текущее расположение)...",
    "Shipping information": "Информация о доставке",
    "Review and payment information": "Review and payment information",
    "Order information": "Информация о заказе",
    "You can create an account after checkout.": "Вы можете создать аккаунт после оформления заказа.",
    "Looks like you already have account with us, please, log in!": "Кажется, у Вас уже есть аккаунт, пожалуйста, войдите в него!",
    "First Name": "Имя",
    "Last Name": "Фамилия",
    "Company": "Компания",
    "Street Address": "Улица",
    "City": "Город",
    "State": "Область",
    "Postal Code": "Почтовый индекс",
    "Country": "Страна",
    "Welcome back!": "С возвращением!",
    "New to our site?": "Впервые на нашем сайте?",
    "Sign up!": "Sign up!",
    "Email": "Email",
    "Enter you e-mail": "Введите свой e-mail",
    "Password": "Пароль",
    "Enter your password": "Введите свой пароль",
    "Sign in with Google": "Войти с помощью Google",
    "Welcome!": "Добро пожаловать!",
    "I already have an account": "У меня уже есть аккаунт",
    "First name": "Имя",
    "Enter you first name": "Введите свое имя",
    "Last name": "Фамилия",
    "Enter you last name": "Введите свою фамилию",
    "Enter you password": "Введите свой пароль",
    "Confirm your password": "Подтвердите свой пароль",
    "Password confirmation": "Подтверждение пароля",
    "Subscribe to the newsletter": "Подписаться на рассылку",
    "I agree to the": "Я согласен с ",
    "terms of the contract": "условиями договора",
    "Sign up": "Зарегистрироваться",
    "New to our site? ": "Впервые на нашем сайте? ",
    "Category page": "Страница категории",
    "Product Thumbnail": "Миниатюра товара",
    "Add to cart": "Добавить в корзину",
    "Adding...": "Добавляется...",
    "Add": "Добавить",
    "Related products": "Похожие товары",
    "Awful": "Ужасно",
    "Bad": "Bad",
    "Average": "Усредненно",
    "Good": "Хорошо",
    "Awesome": "Прекрасно!",
    "Product Review Form": "Форма отзывы",
    "Send review": "Оставить отзыв",
    "Product Actions": "Product Actions",
    "Size & Fit": "Размер и посадка",
    "Fabric & Care": "Ткань и уход",
    "Main product details": "Основная информация о товаре",
    "Product description": "Описание товара",
    "Product Review List": "Отзывы о товаре",
    "Reviews": "Отзвывы",
    "SKU:": "Арикул:",
    "You have not placed any orders yet.": "Вы пока не сделали ни одного заказа.",
    "Complete the look": "Создай комплект",
    "Thank you for your purchase!": "Спасибо за ваш заказ.",
    "Your order # is:": 'Номер Вашего заказа',
    "We`ll email you an order confirmation with details and tracking info.": " Когда ваш заказ будет отправлен Вы получите информацио об отправке на Ваш e-mail. Нажмите здесь, чтобы напечатать копию Вашего заказа.",
    "Invite friend": "Пригласить Друга",
    "Category": "Категории",
    "Buy now": "Купить сейчас",
    "Dress your mailbox": "Приправьте свой почтовый ящик",
    "Subscribe": "Подписаться",
    "Register": "Зарегистрироваться",
    "Phone": "Телефон",
    "Phone *": "Телефон *",
    "Remember me": "Запомнить меня",
    "Don't have an account?": "Нет аккаунта?",
    "Have already registered?": "Уже зарегистрированы?",
    "New user": "Новый пользователь",
    "Login": "Логин",
    "Selected %s of %s": "Выбрано %s из %s",
    "Clear": "Очистить",
    "Price": "Цена",
    "Clear filters": "Очистить фильтры",
    "Shopping cart": "Корзина",
    "Name": "Название",
    "Name ": "Имя",
    "Cost": "Цена",
    "Quantity": "Количество",
    "To checkout": "Перейти к оплате",
    "Total sum:": "Вся сумма:",
    "Coupon Code": "Промо код",
    "products": "товаров",
    "Subscribe to our newsletter to find out about new product releases, %s self-reminders and a 15% discount %s on your next order": "Подпишитесь на нашу рассылку, чтобы узнавать о новых выпусках продуктов, %s напоминаниях о любви к себе и скидке 15% %s на следующий заказ",
    "To sort": "Сортировать",
    "Sort": "Сортировка",
    "Filters": "Фильтры",
    "See products": "Посмотреть товары",
    "From low to high": "От низкой к высокой",
    "From high to low": "От высокой к низкой",
    "First new": "Сначала новые",
    "First old": "Сначала старые",
    "New Products": "Новинки",
    "Sale Products": "Распродажа",
    "Additional Type Products": "Продукты дополнительного типа",
    "Characteristic": "Характеристика",
    "Product %s thumbnail.": "Продукт %s миниатюра.",
    "Results for:": "Результаты для:",
    "Start typing to see search results!": "Начните писать чтобы увидеть результаты поиска",
    "Website subscribe content": "Контент подписки сайта",
    "New": "New",
    "Lubricant": "Лубрикант",
    "Product list navigation": "Навигация списка продуктов",
    "Page %s": "Страница %s",
    "Image not specified": "Изображение не указано",
    "We are sorry!": "Мы сожалеем!",
    "There were no products found matching your request.": "По вашему запросу товаров не найдено.",
    "Please, try removing selected filters and try again!": "Пожалуйста, удалите выбранные фильтры и попробуйте снова!",
    "No results found!": "Ничего не найдено!",
    "Home": "Главная",
    "User data": "Личные данные",
    "Shipping": "Доставка",
    "Billing": "Оплата",
    "Personal data": "Персональные данные",
    "Phone number": "Телефон",
    "Back to cart": "Вернуться к корзине",
    "Next": "Далее",
    "Products": "Товары",
    "Have a promo code?": "Есть промокод?",
    "Cart Subtotal": "Сумма",
    "Order Total": "Вся сумма",
    "Featured Products": "Рекомендации",
    "N/A": '-',
    "Profile": "Профиль",
    "My orders": "Заказы",
    "Address book": "Адресная информация",
    "My wishlist": "Сохраненные товары",
    "My Account": "Мой аккаунт",
    "My Account page": "Страница моего аккаунта",
    "Logout": "Выйти",
    "Current Password": "Текущий пароль",
    "Change Password": "Сменить пароль",
    "Save changes": "Сохранить изменения",
    "Add address": "Добавить адрес",
    "You have no configured addresses.": "У вас нет настроенных адресов.",
    "Wishlist is empty!": "Список избранного пуст!",
    "Continue shopping": "Вернуться к покупкам",
    "Need help?": "Нужна помощь?",
    "Upsell products": "Сопутствующие товары",
    "Add product review": "Добавить отзыв на продукт",
    "Write a review": "Написать отзыв",
    "Recommends": "Рекомендации",
    "Payment and delivery methods": "Способы оплаты и доставки",
    "Add to Wishlist": "Добавить в избранное",
    "Remove from Wishlist": "Удалить из избранного",
    "Customer reviews": "Отзывы покупателей",
    "%s - Picture #%s": "%s - Изображение #%s",
    "See all": "Смотреть всё",
    "Hide": "Скрыть",
    "Delivery": "Доставка",
    // "Shipping": "Доставка",
    "Zip/Postal code": "Код почты",
    "Street address": "Улица",
    "Back to information": "Вернуться к информации",
    "There are no shipping methods available, try different address.": "Нет доступных способов доставки. Попробуйте другой адрес",
    "Select shipping address": "Выберите способ доставки",
    "Type a new search": "Поиск...",
    "Subscribe to our instagram": "Подписывайтесь на наш инстаграм",
    // "My billing and shipping are the same": "Мой биллинг и доставка одинаковы",
    "Complete order": "Подтвердить",
    "Please sign in first!": "Сперва авторизируйтесь на сайте",
    "Submit Review": "Отправить отзыв",
    "Write a name": "Напишите имя",
    "Write a review ": "Напишите отзыв",
    "impossible to edit": "невозможно редактировать",
    "View order": "Посмотреть заказ",
    "Order number": "Номер заказа",
    "Order date": "Дата заказа",
    "All orders": "Все заказы",
    "Brands": "Бренды",
    "Contact online manager": "Связаться с менеджером онлайн",
    "Add a review": "Оставьте отзыв",
    "Payment method": "Метод оплаты",
    "Rate the product": "Оцените товар",
    "Your e-mail": "Ваш e-mail",
    "Brands slider": 'Слайдер "Бренды"',
    "Shipping and payment information": "Информация о доставке и оплате",
    "Back to shipping": "Вернуться К доставке",
    "You are successfully logged in!": "Вы успешно авторизировались!",
    "You are successfully logged out!": "Вы успешно вышли из системы!",
    "Email *": "Email *",
    "Ooops!": "Упс!",
    "Oops": "Упс",
    "Something went wrong!": "Что-то пошло не так",
    "Page not found": "Страница не найдена",
    "Sorry, we can`t find the page you are looking for! Please press a button to come back to homepage.": "Извините, мы не можем найти страницу, которую вы ищете! Пожалуйста, нажмите кнопку ниже, чтобы вернуться на домашнюю страницу.",
    "Back to homepage": "Вернуться на главную",
    "Orders": "Заказы",
    "Account": "Аккаунт",
    "Payment was successful": "Оплата прошла успешно",
    "There are no products in cart.": "В корзине пока что ничего нет",
    "Payment details": "Детали оплаты",
    "You can pick up your order at our store:": "Вы можете забрать ваш заказ по адресу нашего магазина:",
    "including weekends and holidays.": ", включая выходные и праздники.",
    "Warehouses": "Склады",
    "Product Amount": "Сумма товара",
    "Amount": "Сумма",
    "Total amount": "Вся сумма",
    "Delivery Data": "Данные доставки",
    "Delivery address:": "Адрес доставки:",
    "Delivery Method:": "Метод доставки:",
    "Are you 18 years old?": "Вам есть 18 лет?",
    "Yes": "Да",
    "No": "Нет",
    "Sorry, the site contains content": "Извините, сайт содержит контент",
    "that is prohibited": "запрещенный",
    "for viewing by persons": "к ознакомлению лицам",
    "under 18 years of age": "младше 18 лет",
    "Show more": "Показать больше",
    "Show previous": "Показать предыдущие",
    "Blog": "Блог",
    "Back to list": "Вернуться к списку",
    "Pay": "Оплата",
    "Order #%s": "Заказ #%s",
    "Save address": "Сохранить изменения",
    "More articles": "Еще статьи",
    "New publications first": "Сначала новые публикации",
    "Old publications first": "Сначала старые публикации",
    "Select category": "Выбрать рубрику",
    "Sorry, there were no articles found matching your request": "К сожалению, не найдено статей, соответствующих вашему запросу",
    "Street": "Улица",
    "Back": "Назад",
    "There are no reviews for this product yet.": "Отзывов об этом товаре пока нет.",
    " of ": " из ",
    "Title": "Заголовок",
    "Write a title": "Напишите заголовок",
    "Would you recommend this product?": "Рекомендуете ли вы этот товар?",
    "Search...": "Поиск",
    "From old date": "Дата по возрастанию",
    "From new date": "Дата по убыванию",
    "Lower rating": "Рейтинг по возрастанию",
    "Higher rating": "Рейтинг по убыванию",
    "Load previous": "Загрузить предыдущие",
    "Day of birthday": "Дата рождения",
    "Subscribe to our newsletter": "Подписаться на нашу рассылку",
    "You have no orders.": "Заказов не найдено",
    "Ordered": "Заказано",
    "Delivery Date" : "Дата отправки",
    "House number": "Номер дома",
    "Apartment": "Номер квартиры",
    'Product added to cart!': "Продукт добавлен в корзину",
    'Product has been added to your Wish List!': "Товар добавлен в избранное",
    'Error clearing wish list!': "Ошибка очистки избранного",
    'Product has been removed from your Wish List!': "Товар удален из избранного",
    'Error updating wish list!': "Ошибка обновления избранного",
    'You submitted your review for moderation.': "Ваш отзыв отправлен на модерацию",
    'Error submitting review!': "Ошибка отправки отзыва",
    'Coupon was applied!': "Купон применён",
    'Coupon was removed!': "Купон удалён",
    "Incorrect data! Please resolve all field validation errors.": "Некорректные данные. Пожалуйста, исправьте ошибки валидации",
    "Tracking order": "Отследить заказ",
    "Will be delivered": "Будет доставлен",
    "Status": "Статус",
    "No tracking info": "Нет информации о доставке",
    "Date": "Дата",
    "Order status": "Статус заказа",
    "Activity": "Активность",
    "If there is an account associated with the provided address you will receive an email with a link to reset your password.": "Если с указанным адресом связана учетная запись, вы получите электронное письмо со ссылкой для сброса пароля.",
    "You must login or register to add items to your wishlist.": "Вы должны войти в систему или зарегистрироваться, чтобы добавить элементы в свой список пожеланий.",
};
