exports.dictionary = {
    "Sign in": "Увійти",
    "Registration": "Реєстрація",
    "Total": "Всього",
    "Subtotal": "Проміжний підсумок",
    "Color": "Колір",
    "Your cart": "Кошик",
    "Sort By:": "Сортувати за:",
    "Categories": "Категорії",
    "Forgot password?": "Забули пароль?",
    "Product Details": "Информація про товар",
    "Reviews (%s)": "Відгуки (%s)",
    "Step %s": "Крок %s",
    "Website footer content": "Вміст колонтитулу веб-сайту",
    "Website copyright": "Авторські права на веб-сайт",
    "Top header content": "Зміст верхнього заголовка",
    "Header Logo": "Логотип заголовка",
    "Main website navigation": "Основна навігація на веб-сайті",
    "Header search bar": "Рядок пошуку заголовка",
    "MiniCart Icon": "MiniCart значок",
    "Checkout heading": "Заголовок замовлення",
    "Checkout": "Оформлення замовлення",
    "Step indicator": "Покроковий індикатор",
    "Checkout page": "Сторінка оформлення замовлення",
    "Email Address": "Email адреса",
    "Shipping Address": "Адреса доставки",
    "Shipping Method": "Спосіб доставки",
    "Please enter shipping address information first!": "Будь ласка, введіть спочатку інформацію про доставку!",
    "Order Summary (%s)": "Сума замовлення (%s)",
    "Cart Thumbnail": "Мініатюра кошика",
    "Color:": "Колір",
    "Qty:": "Кількість:",
    "Tax": "Податок",
    "Shipping": "Доставка",
    "Product Price": "Ціна товару",
    "Current product price": "Поточна ціна товару",
    "Old product price": "Попередня ціна товару",
    "off": "off",
    "Email is invalid.": "Email недійсний.",
    "Password should be at least 8 characters long, include at least on upper case letter, number and symbol!": "Пароль повинен бути не менше 8 символів, містити принаймні одну велику літеру та цифру!",
    "Phone number is invalid!": "Номер телефону недійсний!",
    "This field is required!": "Це поле є обов'язковим!",
    "No products found!": "Не знайдено жодного товару!",
    "Breadcrumbs (current location)...": "Хлібні крихти (поточне місцезнаходження)...",
    "Shipping information": "Інформація про доставку",
    "Review and payment information": "Огляд та платіжна інформація",
    "Order information": "Інформація по замовленню",
    "You can create an account after checkout.": "Ви можете створити аккаунт після оформлення замовлення.",
    "Looks like you already have account with us, please, log in!": "Здається, у Вас вже є аккаунт! Будь ласка, увійдіть на сайт!!",
    "First Name": "Ім’я ",
    "Last Name": "Прізвище",
    "Company": "Компанія",
    "Street Address": "Вулиця",
    "City": "Місто",
    "State": "Область",
    "Postal Code": "Поштовий індекс",
    "Country": "Країна",
    "Welcome back!": "З поверненням!",
    "New to our site?": "Вперше на нашому сайті?",
    "Sign up!": "Зареєструватися!",
    "Email": "Email",
    "Enter you e-mail": "Введіть свій e-mail",
    "Password": "Пароль",
    "Enter your password": "Введите свой пароль",
    "Sign in with Google": "Увійти з Google",
    "Welcome!": "Ласкаво просимо!",
    "I already have an account": "В мене вже є аккаунт",
    "First name": "Ім’я",
    "Enter you first name": "Введіть своє ім’я",
    "Last name": "Прізвище",
    "Enter you last name": "Введіть своє прізвище",
    "Enter you password": "Введіть свій пароль",
    "Confirm your password": "Підтвердіть свой пароль",
    "Password confirmation": "Підтвердження пароля",
    "Subscribe to the newsletter": "Підписатися на розсилку",
    "I agree to the": "Я згоден з ",
    "terms of the contract": "умовами договору",
    "Sign up": "Зареєструватися!",
    "New to our site? ": "Вперше на нашому сайті? ",
    "Category page": "Сторінка категорії",
    "Product Thumbnail": "Мініатюра товару",
    "Add to cart": "Додати у кошик",
    "Adding...": "Додається...",
    "Related products": "Схожі товари",
    "Awful": "Жахливо",
    "Bad": "Погано",
    "Average": "Середне",
    "Good": "Добре",
    "Awesome": "Чудово",
    "Product Review Form": "Форма відгуку",
    "Send review": "Надіслати відгук",
    "Product Actions": "Product Actions",
    "Size & Fit": "Розмір та посадка",
    "Fabric & Care": "Матеріал та догляд",
    "Main product details": "Загальна  інформація про товар",
    "Product description": "Опис товару",
    "Product Review List": "Відгуки про товар",
    "Reviews": "Відгуки",
    "SKU:": "Артикул::",
    "Complete the look": "Підбери образ",
    "Thank you for your purchase!": 'Дякуємо за покупку!',
    "Your order # is:": 'Номер Вашого замовлення',
    "We`ll email you an order confirmation with details and tracking info.": " Коли ваше замовлення буде вiдправлене Ви отримаєте iнформацiю про вiдправку на Ваш e-mail.  Натиснiть тут, щоб надрукувати копiю Вашого замовлення.",
    "Invite friend": "Запросити Друга",
    "Category": "Категорії",
    "Buy now": "Купити зараз",
    "Subscribe": "Підписатися",
    "Register": "Зареєструватися",
    "Remember me": "Запам'ятати мене",
    "Don't have an account?": "Немає облікового запису?",
    "Dress your mailbox": "Приправте свою почтову скриньку",
    "Have already registered?": "Вже зареєстровані?",
    "New user": "Новий користувач",
    "Login": "Логін",
    "Selected %s of %s": "Вибрано %s з %s",
    "Clear": "Очистити",
    "Price": "Ціна",
    "Shopping cart": "Кошик",
    "Clear filters": "Очистити фільтри",
    "Name": "Назва",
    "Cost": "Ціна",
    "Quantity": "Кількість",
    "To checkout": "Перейти до оплати",
    "Total sum:": "Вся сума:",
    "Coupon Code": "Промо код",
    "products": "товарів",
    "Add": "Додати",
    "Subscribe to our newsletter to find out about new product releases, %s self-reminders and a 15% discount %s on your next order": "Підпишіться на нашу розсилку, щоб дізнаватися про нові випуски продуктів, %s нагадуваннях про любов до себе і знижці 15% %s на наступне замовлення",
    "To sort": "Сортувати",
    "Sort": "Сортування",
    "Filters": "Фільтри",
    "See products": "Подивитися товари",
    "From low to high": "Від низької до високої",
    "From high to low": "Від високої до низької",
    "First new": "Спочатку нові",
    "First old": "Спочатку старі",
    "New Products": "Новинки",
    "Sale Products": "Розпродаж",
    "Additional Type Products": "Продукти додаткового типу",
    "Characteristic": "Характеристика",
    "Product %s thumbnail.": "Продукт %s мініатюра.",
    "Results for:": "Результати для:",
    "Start typing to see search results!": "Почніть писати щоб побачити результати пошуку",
    "Website subscribe content": "Контент підписки сайту",
    "New": "New",
    "Lubricant": "Лубрикант",
    "Product list navigation": "Навігація списку продуктів",
    "Page %s": "Сторінка %s",
    "Image not specified": "Зображення не вказано",
    "We are sorry!": "Ми шкодуємо!",
    "There were no products found matching your request.": "По вашому запиту товарів не знайдено.",
    "Please, try removing selected filters and try again!": "Будь ласка, видаліть вибрані фільтри і спробуйте знову!",
    "No results found!": "Нічого не знайдено!",
    "Home": "Головна",
    "User data step": "Етап введення персональних даних",
    "Shipping step": "Етап вибору доставки",
    "Billing": "Оплата",
    "Personal data": "Персональні дані",
    "Phone number": "Номер телефону",
    "Back to cart": "Назад до кошику",
    "Next": "Далі",
    "Products": "Продукти",
    "Have a promo code?": "Є промокод?",
    "Cart Subtotal": "Сума кошика",
    "Order Total": "Сума замовлення",
    "Featured Products": "Рекомендоване",
    "N/A": '-',
    "Profile": "Профіль",
    "My orders": "Замовлення",
    "Address book": "Адресна інформація",
    "My wishlist": "Вибрані товари",
    "My Account": "Мій аккаунт",
    "My Account page": "Сторінка мого аккаунта",
    "Logout": "Вийти",
    "Current Password": "Поточний пароль",
    "Change Password": "Змінити пароль",
    "Save changes": "Зберегти зміни",
    "Add address": "Додати адресу",
    "You have no configured addresses.": "У вас немає налаштованих адрес.",
    "Wishlist is empty!": "Список обраного порожній!",
    "Continue shopping": "Повернутися до покупок",
    "Need help?": "Потрібна допомога?",
    "Phone": "Телефон",
    "Phone *": "Телефон *",
    "Upsell products": "Супутні товари",
    "Add product review": "Додати відгук на продукт",
    "Write a review": "Написати відгук",
    "Recommends": "Рекомендації",
    "Payment and delivery methods": "Способи оплати і доставки",
    "Add to Wishlist": "Додати в обране",
    "Remove from Wishlist": "Видалити з обраного",
    "Customer reviews": "Відгуки клієнтів",
    "%s - Picture #%s": "%s - Зображення #%s",
    "See all": "Дивитись все",
    "Hide": "Приховати",
    "Type a new search": "Пошук...",
    "Search...": "Пошук...",
    "Subscribe to our instagram": "Підписуйтесь на наш інстаграм",
    "User data": "Особисті дані",
    "Complete order": "Підтвердити",
    "My billing and shipping are the same": "",
    "Please sign in first!": "Спочатку авторизуйтеся на сайті",
    "impossible to edit": "неможливо редагувати",
    "View order" : "Дивитися замовлення",
    "Order number": "Номер замовлення",
    "Order date": "Дата замовлення",
    "All orders": "Всі замовлення",
    "Brands": "Бренди",
    "Contact online manager": "Зв'язатися з онлайн-менеджером",
    "Add a review": "Залиште відгук",
    "Rate the product": "Оцініть товар",
    "Your e-mail": "Ваш e-mail",
    "Brands slider": 'Слайдер "Бренди"',
    "Shipping and payment information": "Інформація про доставку і оплату",
    "Back to shipping": "Повернутися до доставки",
    "You are successfully logged in!": "Ви успішно авторизувались!",
    "You are successfully logged out!": "Ви успішно вийшли з системи!",
    "Email *": "Email *",
    "Ooops!": "Упс!",
    "Oops": "Упс",
    "Something went wrong!": "Щось пішло не так",
    "Back to homepage": "Повернуться на головну",
    "Page not found": "Сторінка не знайдена",
    "Sorry, we can`t find the page you are looking for! Please press a button to come back to homepage.": "Вибачте, ми не можемо знайти сторінку, яку ви шукаєте! Будь ласка, натисніть кнопку нижче, щоб повернутися на домашню сторінку.",
    "Orders": "Замовлення",
    "Account": "Акаунт",
    "Delivery": "Доставка",
    "Zip/Postal code": "Поштовий індекс",
    "Street address": "Вулиця",
    "Back to information": "Повернутися до інформації",
    "Payment was successful": "Оплата пройшла успішно",
    "There are no products in cart.": "У кошику поки що нічого нема",
    "Payment details": "Деталі оплати",
    "You can pick up your order at our store:": "Ви можете забрати ваше замовлення за адресою нашого магазину:",
    "including weekends and holidays.": ", вихідні та свята включно.",
    "Warehouses": "Склади",
    "Product Amount": "Сумма товару",
    "Amount": "Сумма",
    "Total amount": "Вся сума",
    "Delivery Data": "Дані доставки",
    "Delivery address:": "Адреса доставки:",
    "Delivery Method:": "Метод доставки:",
    "Are you 18 years old?": "Вам є 18 років?",
    "Yes": "Так",
    "No": "Ні",
    "Pay": "Оплата",
    "Order #%s": "Замовлення #%s",
    "Save address": "Зберегти зміни",
    "Payment method": "Спосіб оплати",
    "Sorry, the site contains content": "Вибачте, сайт містить контент",
    "that is prohibited": "заборонений",
    "for viewing by persons": "до ознайомлення особам",
    "under 18 years of age": "молодше 18 років",
    "Show more": "Показати більше",
    "Show previous": "Показати попередні",
    "Blog": "Блог",
    "Back to list": "Повернутися до списку",
    "More articles": "Ще статті",
    "New publications first": "Спочатку нові публікації",
    "Old publications first": "Спочатку старі публікації",
    "Select category": "Вибрати рубрику",
    "Sorry, there were no articles found matching your request": "На жаль, не знайдено статей, що відповідають вашому запиту",
    "There are no reviews for this product yet.": "Відгуків про цей товар поки немає.",
    " of ": " з ",
    "Title": "Заголовок",
    "Write a title": "Напишіть заголовок",
    "Would you recommend this product?": "Чи рекомендуєте ви цей товар?",
    "Back": "Назад",
    "Street": "Вулиця",
    "Name ": "Ім’я",
    "Write a name": "Напишіть ім’я",
    "Review": "Відгук",
    "Write a review ": "Напишіть відгук",
    "Submit Review": "Залишити відгук",
    "From old date": "Дата по зростанню",
    "From new date": "Дата за спаданням",
    "Lower rating": "Рейтинг по зростанню",
    "Higher rating": "Рейтинг за спаданням",
    "Load previous": "Завантажити попередні",
    "Day of birthday": "Дата народження",
    "Subscribe to our newsletter": "Підписатися на нашу розсилку",
    "You have no orders.": "Замовлень не знайдено",
    "Ordered": "Замовлено",
    "Delivery Date" : "Дата відправки",
    "House number": "Номер будинку",
    "Apartment": "Номер квартири",
    "Tracking order": "Відстежити замовлення",
    "Will be delivered": "Буде доставлений",
    "Status": "Статус",
    "No tracking info": "Немає інформації про доставку",
    "Date": "Дата",
    "Order status": "Статус замовлення",
    "Activity": "Активність",
    "If there is an account associated with the provided address you will receive an email with a link to reset your password.": "Якщо з вказаною адресою пов'язана обліковий запис, ви отримаєте електронного листа з посиланням для скидання пароля.",
    "You must login or register to add items to your wishlist.": "Ви повинні увійти в систему або зареєструватися, щоб додати елементи в свій список побажань.",
    'Product added to cart!': "Товар додано в кошик",
    'Product has been added to your Wish List!': "Товар додано в обране",
    'Error clearing wish list!': "Помилка очистки обраного",
    'Product has been removed from your Wish List!': "Товар видалено з обраного",
    'Error updating wish list!': "Помилка оновлення обраного",
    'You submitted your review for moderation.': "Ваш відгук відправлено на модерацію",
    'Error submitting review!': "Помилка відправки відгуку",
    'Coupon was applied!': "Купон застосовано",
    'Coupon was removed!': "Купон видалено",
    "Incorrect data! Please resolve all field validation errors.": "Некоректні дані. Будь ласка, виправте помилки валдації",
};
